---
- name: Set current role path
  ansible.builtin.set_fact:
    current_role_path: '{{ role_path }}'

- name: Ensure SSH directory exists
  ansible.builtin.file:
    path: /home/ansible/.ssh
    state: directory
    mode: '0700'
  delegate_to: localhost

- name: Write SSH private key to file
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: /home/ansible/.ssh/id_rsa
    mode: '0600'
  delegate_to: localhost

- name: Write SSH public key to file
  ansible.builtin.copy:
    content: "{{ ssh_public_key }}"
    dest: /home/ansible/.ssh/id_rsa.pub
    mode: '0644'
  delegate_to: localhost

- name: Add SSH key to agent
  ansible.builtin.shell: |
    eval "$(ssh-agent -s)"
    ssh-add /home/ansible/.ssh/id_rsa
  delegate_to: localhost

- name: Set InSpec attributes
  when: inspec_vars_list is defined
  block:
    - ansible.builtin.set_fact:
        inspec_attr_path: /tmp/inspec-attr-{{ inventory_hostname }}-{{ ansible_date_time.iso8601_basic }}.yml
        inspec_attr_list: "{% for v in inspec_vars_list %}{{v.name}} : {{v.value}}\n{% endfor %}"

    - name: Dump vars to file
      ansible.builtin.copy:
        content: '{{ inspec_attr_list }}'
        dest: '{{ inspec_attr_path }}'
      changed_when: false
      delegate_to: localhost

- ansible.builtin.set_fact:
    inspec_attr_arg: "{{ '--input-file %s'|format(inspec_attr_path) if inspec_vars_list is defined else '' }}"

- name: Set InSpec profiles path
  ansible.builtin.set_fact:
    inspec_profile_dir: '{{ current_role_path }}/inspec-profile'
  when: inspec_profile_dir is undefined

- name: Ensure InSpec results directory exists on target
  ansible.builtin.file:
    path: /tmp/inspec-results
    state: directory
    mode: '0755'

- name: Run InSpec tests
  ansible.builtin.shell: |
    eval "$(ssh-agent -s)"
    ssh-add /home/ansible/.ssh/id_rsa
    inspec exec {{ inspec_profile_dir }} \
    -t ssh://{{ ansible_user }}@{{ ansible_host }} \
    --key-files /home/ansible/.ssh/id_rsa \
    {{ inspec_attr_arg }} \
    --reporter json:/tmp/inspec-results/inspec_results.json
  delegate_to: localhost
  changed_when: false
  register: inspec_out
  ignore_errors: yes
  environment:
    CHEF_LICENSE: "{{ chef_license }}"
    CHEF_LICENSE_KEY: "{{ chef_license_key }}"

- name: Fetch InSpec results to local machine
  ansible.builtin.fetch:
    src: /tmp/inspec-results/inspec_results.json
    dest: /tmp/inspec_results_{{ inventory_hostname }}.json
    flat: yes

- name: Cleanup temporary InSpec files on target
  ansible.builtin.file:
    path: /tmp/inspec-results/inspec_results.json
    state: absent

- name: Display InSpec summary
  ansible.builtin.debug:
    msg: "InSpec run completed. Results stored in /tmp/inspec_results_{{ inventory_hostname }}.json"
  when: inspec_out.rc == 0 or inspec_out.rc == 101

- name: Read the InSpec results
  ansible.builtin.slurp:
    src: /tmp/inspec_results_{{ inventory_hostname }}.json
  register: inspec_results_content

- name: Display the InSpec results content
  ansible.builtin.debug:
    msg: "{{ inspec_results_content['content'] | b64decode }}"
  when: inspec_results_content is defined

